#title:Which classes have instances?
#comment:Counts the number of instances per class
#tags:class, instance

SELECT ?class (count(?instance) AS ?numberOfInstances)
WHERE {
    ?instance a ?class .
}
GROUP BY ?class
ORDER BY desc(?numberOfInstances)
