#title:Which classes use a particular property?
#comment:In this example we see which classes use prov:qualifiedAssociation
    
SELECT DISTINCT ?class
WHERE {
    ?subject prov:qualifiedAssociation ?o .
	?subject a ?class .
}

# It is a good practice to include rdfs:label, rdfs:comment or 
# rdfs:domain to describe data
