#title:Get replaced environment attributes
#comment:This returns all environment attributes that have been modified (i. e. "replaced" = removed and added) between the two trial executions. Additional information such as old and new values and IDs are also provided.
#command:now diff -p -e --format turtle 7 1
#tags:noworkflow,order,blank node,diff
#color:ex-green

SELECT ?name ?old_id ?old_value ?new_id ?new_value
WHERE {
 ?addedAttr a prov:Entity, "environmentAttribute" ;
			rdfs:label ?name ;
			prov:qualifiedRevision ?revisionNode ;
			prov:value ?new_value ;
			ns1:id ?new_id .
  
 ?revisionNode a prov:Revision, "environmentAttributeReplacement" ;
			   prov:entity ?removedAttr .
  
 ?removedAttr a prov:Entity, "environmentAttribute" ;
			  prov:value ?old_value ;
			  ns1:id ?old_id .
				 
}
ORDER BY ?name
